# Generated by Django 5.2.4 on 2025-07-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
