# Generated by Django 5.2.4 on 2025-08-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
