# Generated by Django 5.2.4 on 2025-08-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(default='Địa chỉ chưa cập nhật', max_length=255),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shipper_info',
            field=models.CharField(default='Thông tin shipper chưa cập nhật', max_length=255),
        ),
    ]
