# Generated by Django 5.2.4 on 2025-08-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
