# Generated by Django 5.2.4 on 2025-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_restaurantregistration_restaurant_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='permissions',
            field=models.CharField(choices=[('full', 'Full'), ('registrations', 'Manage Registrations'), ('restaurants', 'Manage Restaurants')], default='full', max_length=20),
        ),
    ]
